---
edge_gateway_base_path: "/opt/edge-gateway"
edge_gateway_email: ""
edge_gateway_network: "edge-net"

# Backward compatibility (manual apps)
edge_gateway_apps: []

# Phase 2.3 â€” service label discovery
edge_gateway_docker_label: "edge.enable=true"
