---
edge_gateway_base_path: "/opt/edge-gateway"
edge_gateway_email: ""
edge_gateway_network: "edge-net"

# manual fallback (kept for compatibility)
edge_gateway_apps: []

# ELITE auto-discovery label
edge_gateway_docker_label: "edge.enable=true"
