---
- name: Deploy Edge Gateway
  hosts: edge_gateway_servers
  become: true

  roles:
    - role: edge_gateway
      vars:
        edge_gateway_email: rwabig1@gmail.com
        edge_gateway_domains:
          - vscode.unifypesacard.shop
          - cgs.unifypesacard.shop


[ERROR]: the role 'edge_gateway' was not found in /home/ubuntu/Ram/ansible/playbooks/roles:/roles:/home/ubuntu/Ram/ansible/playbooks
Origin: /home/ubuntu/Ram/ansible/playbooks/edge-gateway.yml:7:7

5
6   roles:
7     - role: edge_gateway
        ^ column 7
